# Generated by Django 3.1.7 on 2021-03-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='note',
            field=models.CharField(default='<django.db.models.fields.DateTimeField>', max_length=100),
        ),
    ]
